[package]
name = "onboard"
version = "5.1.3"
edition = "2018"
authors = ["0L contributors"]
description = "0L onboarding wizard"
repository = "https://github.com/OLSF/libra"
homepage = "https://github.com/olsf/"

[dependencies]
wait-timeout = "0.2.0"
gumdrop = "0.7"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
serde_json = "1"
diem-wallet = { path = "../../testsuite/cli/diem-wallet" }
diem-types = { path = "../../types/" }
rustyline = "6.2.0"
anyhow = "1.0.31"
toml = "0.5.6"
reqwest = { version = "0.11.2", features = ["blocking", "json"], default_features = false }
diem-global-constants = { path = "../../config/global-constants"}
dirs = "2.0.2"
diem-genesis-tool = { path = "../../config/management/genesis" }
diem-crypto = { path = "../../crypto/crypto" }
ol-keys = { path = "../keys/" }
ol = { path = "../cli"}
txs = { path = "../txs"}
ol-types = { path = "../../ol/types"}
bcs = "0.1.2"
hex ="*"
tower = { path = "../tower" }
zip = "0.5.12"
dialoguer = "0.8.0"

[dependencies.abscissa_core]
version = "0.5.2"

[dev-dependencies]
abscissa_core = { version = "0.5.2", features = ["testing"] }
once_cell = "1.2"
criterion = "0.3"