[package]
name = "vm-genesis"
version = "0.1.0"
edition = "2018"
authors = ["Libra Association <opensource@diem.org>"]
description = "Libra vm genesis"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.33"
once_cell = "1.4.1"
rand = "0.7.3"
hex = "0.4"
serde = { version = "1.0.116", features = ["rc"], default-features = false }

bytecode-verifier = { path = "../../bytecode-verifier", version = "0.1.0" }
lcs = { path = "../../../common/lcs", version = "0.1.0", package = "diem-canonical-serialization" }
diem-config = { path = "../../../config", version = "0.1.0" }
diem-crypto = { path = "../../../crypto/crypto", version = "0.1.0" }
diem-state-view = { path = "../../../storage/state-view", version = "0.1.0" }
diem-types = { path = "../../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
diem-network-address = { path = "../../../network/network-address", version = "0.1.0" }
move-core-types = { path = "../../move-core/types", version = "0.1.0" }
move-vm-runtime = { path = "../../move-vm/runtime", version = "0.1.0"}
move-vm-types = { path = "../../move-vm/types", version = "0.1.0" }
compiled-stdlib = { path = "../../stdlib/compiled",  version = "0.1.0" }
transaction-builder = { path = "../../transaction-builder", version = "0.1.0"}
vm = { path = "../../vm", version = "0.1.0" }
diem-vm = { path = "../../diem-vm", version = "0.1.0" }

[dev-dependencies]
proptest = "0.10.1"
proptest-derive = "0.2.0"
diem-proptest-helpers = { path = "../../../common/proptest-helpers", version = "0.1.0" }

[features]
default = []
fuzzing = ["diem-types/fuzzing", "move-vm-types/fuzzing"]
