[package]
name = "move-ir-types"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
description = "Types for Move IR"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
codespan = { version = "0.8.0", features = ["serialization"] }
serde = { version = "1.0.116", features = ["derive"] }
hex = "0.4.2"
once_cell = "1.4.1"

diem-types = { path = "../../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
move-core-types = { path = "../../move-core/types", version = "0.1.0" }
