[package]
name = "storage-interface"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem storage interface"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
itertools = "0.10.0"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
parking_lot = "0.11.1"

bcs = "0.1.2"
diem-crypto = { path = "../../crates/diem-crypto" }
diem-secure-net = { path = "../../secure/net" }
diem-state-view = { path = "../state-view" }
diem-types = { path = "../../types" }
diem-workspace-hack = { version = "0.1", path = "../../crates/diem-workspace-hack" }
scratchpad = { path = "../scratchpad" }
move-core-types = { git = "https://github.com/OLSF/move-0L", rev = "5ff91d82a4969f1efa18dfc18965a37300d8f2e4" }

[features]
default = []
fuzzing = ["diem-types/fuzzing"]
