[package]
name = "diem-json-rpc-types"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem JSONRPC Types"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.33"
hex = "0.4.2"
serde = { version = "1.0.116", default-features = false }
serde_json = "1.0.58"

compiled-stdlib = { path = "../../language/stdlib/compiled",  version = "0.1.0" }
lcs = { path = "../../common/lcs", version = "0.1.0", package = "diem-canonical-serialization" }
diem-types = { path = "../../types", version = "0.1.0" }
diem-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
move-core-types = { path = "../../language/move-core/types", version = "0.1.0" }
transaction-builder = { path = "../../language/transaction-builder", version = "0.1.0"}
move-explain = { path = "../../language/tools/move-explain", version = "0.1.0" }
