[package]
name = "stdlib"
version = "0.1.0"
edition = "2018"
authors = ["Libra Association <opensource@diem.org>"]
description = "Libra stdlib"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.33"
bytecode-verifier = { path = "../bytecode-verifier", version = "0.1.0" }
move-lang = { path = "../move-lang" }
move-prover = { path = "../move-prover" }
diem-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
diem-types = { path = "../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
datatest-stable = { path = "../../common/datatest-stable", version = "0.1.0" }
lcs = { path = "../../common/lcs", version = "0.1.0", package = "diem-canonical-serialization" }
vm = { path = "../vm", version = "0.1.0" }
transaction-builder-generator = { path = "../transaction-builder/generator", version = "0.1.0" }

clap = "2.33.3"
log = "0.4.11"
rayon = "1.4.1"
sha2 = "0.9.1"

[features]
default = []
fuzzing = ["diem-types/fuzzing"]
