[package]
name = "executor-types"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem executor interface types"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.33"
serde = { version = "1.0.116", default-features = false }
thiserror = "1.0.21"

lcs = { path = "../../common/lcs", version = "0.1.0", package = "diem-canonical-serialization" }
diem-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
diem-secure-net = { path = "../../secure/net", version = "0.1.0" }
diem-types = { path = "../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
scratchpad = { path = "../../storage/scratchpad", version = "0.1.0" }
storage-interface = { path = "../../storage/storage-interface", version = "0.1.0" }

[features]
default = []
fuzzing = ["diem-crypto/fuzzing", "diem-types/fuzzing"]
