[package]
name = "txs"
authors = []
version = "0.1.0"
edition = "2018"

[dependencies]
ajson = "0.2.3"
anyhow = "1.0.31"
byteorder = "1"
dirs = "2.0.2"
glob = "0.3"
gumdrop = "0.7"
hex = "0.4"
regex = "1"
rpassword = "5.0"
rustyline = "6.2.0"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
thiserror = "1"
toml = "0.5.6"
wait-timeout = "0.2.0"

classgroup = { path = "../../ol/verifiable_delay/classgroup", version = "^0.1.0" }
cli = { path = "../../testsuite/cli/", version = "0.1.0" }
compiled-stdlib = { path = "../../language/stdlib/compiled", version = "0.1.0" }
keygen = { path = "../keygen/", version = "0.1.0" }
lcs = { path = "../../common/lcs", version = "0.1.0", package = "libra-canonical-serialization" }
libra-config = { path = "../../config/", version = "0.1.0" }
libra-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
libra-genesis-tool = { path = "../../config/management/genesis", version = "0.1.0" }
libra-global-constants = { path = "../../config/global-constants", version = "0.1.0"}
libra-json-rpc-types = { path = "../../json-rpc/types", version = "0.1.0"} 
libra-logger = { path = "../../common/logger", version = "0.1.0" }
libra-management = { path = "../../config/management", version = "0.1.0" }
libra-network-address = { path = "../../network/network-address", version = "0.1.0" }
libra-types = { path = "../../types/", version = "0.1.0" }
libra-wallet = { path = "../../testsuite/cli/libra-wallet", version = "0.1.0" }
libradb = { path = "../../storage/libradb", version="0.1.0"}
move-core-types={path="../../language/move-core/types", version="0.1.0"}
reqwest = { version = "0.10.6", features = ["blocking", "json"], default_features = false }
stdlib = { path = "../../language/stdlib", version = "0.1.0" }
storage-interface= {path = "../../storage/storage-interface", version="0.1.0"}
transaction-builder = { path = "../../language/transaction-builder", version = "0.1.0"}
vdf = { path = "../../ol/verifiable_delay/vdf", version = "^0.1.0" }
vm-genesis={path="../../language/tools/vm-genesis", version="0.1.0"}
ol-cli = {path = "../cli"}
dialoguer = "0.8.0"
ol-types = {path = "../types"}
ol-fixtures = {path = "../fixtures"}


[dependencies.abscissa_core]
version = "0.5.2"

[dev-dependencies]
abscissa_core = { version = "0.5.2", features = ["testing"] }
criterion = "0.3"
once_cell = "1.2"
