[package]
name = "txs"
authors = []
version = "5.1.3"
edition = "2018"

[dependencies]
ajson = "0.2.3"
anyhow = "1.0.31"
bcs = "0.1.2"
byteorder = "1"
dirs = "2.0.2"
dialoguer = "0.8.0"
glob = "0.3"
gumdrop = "0.7"
hex = "0.4"
regex = "1"
rpassword = "5.0"
rustyline = "6.2.0"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
thiserror = "1"
toml = "0.5.6"
wait-timeout = "0.2.0"

classgroup = { path = "../../ol/verifiable_delay/classgroup", version = "^0.1.0" }
cli = { path = "../../testsuite/cli/" }
diem-config = { path = "../../config/" }
diem-crypto = { path = "../../crypto/crypto" }
diem-genesis-tool = { path = "../../config/management/genesis" }
diem-global-constants = { path = "../../config/global-constants"}
diem-json-rpc-types = { path = "../../json-rpc/types" } 
diem-logger = { path = "../../common/logger" }
diem-management = { path = "../../config/management" }
diem-secure-storage = { path = "../../secure/storage" }
diem-types = { path = "../../types/" }
diem-wallet = { path = "../../testsuite/cli/diem-wallet" }
diemdb = { path = "../../storage/diemdb"}
diem-transaction-builder = { path = "../../sdk/transaction-builder" }
move-core-types={path="../../language/move-core/types"}
ol = {path = "../cli"}
ol-keys = { path = "../keys/", version = "0.1.0" }
ol-types = {path = "../../ol/types"}
resource-viewer = { path = "../../language/tools/resource-viewer", version = "0.1.0" }
reqwest = { version = "0.11.2", features = ["blocking", "json"], default_features = false }
storage-interface= {path = "../../storage/storage-interface"}
vdf = { path = "../../ol/verifiable_delay/vdf", version = "^0.1.0" }
vm-genesis={path="../../language/tools/vm-genesis"}

[dependencies.abscissa_core]
version = "0.5.2"

[dev-dependencies]
abscissa_core = { version = "0.5.2", features = ["testing"] }
criterion = "0.3"
once_cell = "1.2"