[package]
name = "txs"
authors = []
version = "5.0.11"
edition = "2018"

[dependencies]
ajson = "0.2.3"
anyhow = "1.0.31"
bcs = "0.1.2"
byteorder = "1"
dirs = "2.0.2"
dialoguer = "0.8.0"
glob = "0.3"
gumdrop = "0.7"
hex = "0.4"
regex = "1"
rpassword = "5.0"
rustyline = "6.2.0"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
thiserror = "1"
toml = "0.5.6"
wait-timeout = "0.2.0"

classgroup = { path = "../../ol/verifiable_delay/classgroup", version = "^0.1.0" }
diem-client = { path = "../../crates/diem-client" }
diem-config = { path = "../../config/" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-genesis-tool = { path = "../../config/management/genesis" }
diem-global-constants = { path = "../../config/global-constants"}
diem-json-rpc-types = { path = "../../json-rpc/types" } 
diem-logger = { path = "../../crates/diem-logger" }
diem-management = { path = "../../config/management" }
diem-secure-storage = { path = "../../secure/storage" }
diem-types = { path = "../../types/" }
diem-wallet = { path = "../../crates/diem-wallet" }
diemdb = { path = "../../storage/diemdb"}
diem-transaction-builder = { path = "../../sdk/transaction-builder" }
executor-benchmark = { path = "../../execution/executor-benchmark" }
move-core-types = { git = "https://github.com/OLSF/move-0L", rev = "ab8d1dc313b747f813ecc42a388edc198311f14a" }
ol = {path = "../cli"}
ol-keys = { path = "../keys/", version = "0.1.0" }
ol-types = {path = "../../ol/types"}
move-resource-viewer = { git = "https://github.com/OLSF/move-0L", rev = "ab8d1dc313b747f813ecc42a388edc198311f14a" }
reqwest = { version = "0.11.2", features = ["blocking", "json"], default_features = false }
storage-interface= {path = "../../storage/storage-interface"}
vdf = { path = "../../ol/verifiable_delay/vdf", version = "^0.1.0" }
vm-genesis={path="../../diem-move/vm-genesis"}

[dependencies.abscissa_core]
version = "0.5.2"

[dev-dependencies]
abscissa_core = { version = "0.5.2", features = ["testing"] }
criterion = "0.3"
once_cell = "1.2"