[package]
name = "language-e2e-tests"
version = "0.1.0"
edition = "2018"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem language e2e testing framework"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.52"
goldenfile = "1.1.0"
bcs = "0.1.2"
once_cell = "1.7.2"
rand = "0.8.3"
proptest = "1.0.0"
proptest-derive = "0.3.0"
hex = "0.4.3"
serde = { version = "1.0.124", default-features = false }

## Move dependencies
move-core-types = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
move-ir-compiler = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
move-vm-runtime = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
move-vm-types = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
move-binary-format = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
read-write-set = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
move-command-line-common = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }

## Diem-Move dependencies
diem-writeset-generator = { path = "../writeset-transaction-generator" }
vm-genesis = { path = "../vm-genesis" }
diem-vm = { path = "../diem-vm" }
diem-keygen = { path = "../diem-keygen" }
diem-framework-releases = { path = "../diem-framework/DPN/releases" }

## Other Diem Dependencies
diem-crypto = { path = "../../crates/diem-crypto", features = ["fuzzing"] }
diem-state-view = { path = "../../storage/state-view" }
diem-types = { path = "../../types", features = ["fuzzing"] }
diem-proptest-helpers = { path = "../../crates/diem-proptest-helpers" }
diem-config = { path = "../../config" }
diem-transaction-builder = { path = "../../sdk/transaction-builder" }
diem-workspace-hack = { version = "0.1", path = "../../crates/diem-workspace-hack" }
