[package]
name = "ir-to-bytecode-syntax"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
description = "Libra ir to bytecode syntax"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.33"
codespan = { version = "0.8.0", features = ["serialization"] }
hex = "0.4.2"
move-ir-types = { path = "../../../move-ir/types", version = "0.1.0" }
move-core-types = { path = "../../../move-core/types", version = "0.1.0" }
diem-types = { path = "../../../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../../../common/workspace-hack", version = "0.1.0" }

[features]
default = []
fuzzing = ["diem-types/fuzzing"]
