[package]
name = "test-utils"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
prettydiff = "0.3.1"
anyhow = "1.0.33"
regex = "1.3.9"
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
