[package]
name = "diem-transaction-replay"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
description = "Replay transactions stored on chain"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.33"
structopt = "0.3.18"
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
diem-types = { path = "../../../types", version = "0.1.0" }
diem-state-view = { path = "../../../storage/state-view", version = "0.1.0" }
diem-validator-interface = { path = "../diem-validator-interface", version = "0.1.0" }
diemdb = { path = "../../../storage/diemdb", version = "0.1.0" }
diem-vm = { path = "../../diem-vm", version = "0.1.0" }
vm = { path = "../../vm", version = "0.1.0"}
move-vm-types = { path = "../../move-vm/types", version = "0.1.0" }
move-core-types = { path = "../../move-core/types", version = "0.1.0" }
move-vm-runtime = { path = "../../move-vm/runtime", version = "0.1.0" }
move-vm-test-utils = { path = "../../move-vm/test-utils", version = "0.1.0" }
resource-viewer = { path = "../../tools/resource-viewer", version = "0.1.0" }
stdlib = { path = "../../stdlib", version = "0.1.0" }
move-lang = { path = "../../move-lang", version = "0.0.1" }
lcs = { path = "../../../common/lcs", version = "0.1.0", package = "diem-canonical-serialization" }
difference = "2.0.0"

[dev-dependencies]
vm-genesis = { path = "../../tools/vm-genesis", version = "0.1.0" }
compiled-stdlib = { path = "../../stdlib/compiled", version = "0.1.0" }
