[package]
name = "serializer-tests"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
description = "Libra serializer tests"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dev-dependencies]
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
proptest = "0.10.1"
proptest-derive = "0.2.0"
vm = { path = "../", version = "0.1.0", features = ["fuzzing"] }

[features]
fuzzing = ["vm/fuzzing"]
