[package]
name = "tower"
version = "5.1.3"
edition = "2018"
authors = ["0L contributors"]
description = "0L tower"
repository = "https://github.com/OLSF/libra"
homepage = "https://github.com/olsf/"

[dependencies]
bcs = "0.1.2"
wait-timeout = "0.2.0"
gumdrop = "0.7"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
classgroup = { path = "../../ol/verifiable_delay/classgroup" }
vdf = { path = "../../ol/verifiable_delay/vdf" }
hex = { version = "0.4.2", features = ["serde"] }
byteorder = "1"
glob = "0.3"
serde_json = "1"
diem-crypto = { path = "../../crypto/crypto" }
diem-wallet = { path = "../../testsuite/cli/diem-wallet" }
cli = { path = "../../testsuite/cli/" }
diem-types = { path = "../../types/" }
diem-config = { path = "../../config/" }
diem-json-rpc-types = { path = "../../json-rpc/types"} 
diemdb = { path = "../../storage/diemdb"}
diem-logger = { path = "../../common/logger" }
storage-interface= {path = "../../storage/storage-interface"}
vm-genesis={path="../../language/tools/vm-genesis"}
move-core-types={path="../../language/move-core/types"}
regex = "1"
rpassword = "5.0"
ajson = "0.2.3"
rustyline = "6.2.0"
anyhow = "1.0.31"
toml = "0.5.6"
reqwest = { version = "0.11.2", features = ["blocking", "json"], default_features = false }
diem-global-constants = { path = "../../config/global-constants"}
dirs = "2.0.2"
diem-genesis-tool = { path = "../../config/management/genesis" }
diem-management = { path = "../../config/management" }
diem-transaction-builder = { path = "../../sdk/transaction-builder" }
ol-keys = { path = "../keys/" }
url = { version = "^2.1", features = ["serde"]}
diem-secure-storage = { path = "../../secure/storage" }
machine-ip = "0.2.1"
ol = { path = "../cli"}
txs = { path = "../txs"}
ol-types = { path = "../../ol/types"}

[dependencies.abscissa_core]
version = "0.5.2"

[dev-dependencies]
abscissa_core = { version = "0.5.2", features = ["testing"] }
once_cell = "1.2"
criterion = "0.3"

[[bench]]
name = "bench"
harness = false