[package]
name = "transaction-builder"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
description = "Libra transaction-builder"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
edition = "2018"

[dependencies]
mirai-annotations = "1.10.1"

diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
transaction-builder-generated = { path = "../../client/transaction-builder", version = "0.1.0" }

[features]
default = []
