[package]
name = "diem-validator-interface"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
description = "Defines interfaces between the diem nodes and local move infrastructure"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.8", features = ["blocking", "json"] }
anyhow = "1.0.33"
diem-json-rpc-client = { path = "../../../client/json-rpc", version = "0.1.0" }
diem-types = { path = "../../../types", version = "0.1.0" }
diemdb = { path = "../../../storage/diemdb", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
storage-interface = { path = "../../../storage/storage-interface", version = "0.1.0" }
scratchpad = { path = "../../../storage/scratchpad", version = "0.1.0" }
diem-state-view = { path = "../../../storage/state-view", version = "0.1.0" }
lcs = { path = "../../../common/lcs", version = "0.1.0", package = "diem-canonical-serialization" }
