[package]
name = "ol"
authors = []
version = "5.1.3"
edition = "2018"

[dependencies]
bitflags = "1.0"
cassowary = "0.3"
unicode-segmentation = "1.2"
unicode-width = "0.1"
chrono = "0.4.19"
once_cell = "1.7.2"
sysinfo = "0.16.4"
gumdrop = "0.7"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
reqwest = { version = "0.11.2", features = ["blocking", "json"], default_features = false }
cli = { path = "../../testsuite/cli/", version = "0.1.0" }
diem-types = { path = "../../types/" }
num-format = "0.4.0"
resource-viewer = { path = "../../language/tools/resource-viewer", version = "0.1.0" }
anyhow = "1.0"
diem-global-constants = { path = "../../config/global-constants", version = "0.1.0"}
byteorder = "1"
dirs = "2.0.2"
toml = "0.5.6"
rustyline = "6.2.0"
diem-json-rpc-client = { path = "../../client/json-rpc", version = "0.1.0" }
crossterm = "0.19.0"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1.1"
warp = "0.3.0"
serde_json = "1.0"
serde_yaml = "0.8.17"
async-stream = "0.3.1"
clokwerk = "0.3.4"
handlebars = "3.5.3"
futures = "0.3.6"
nix = "*"
diem-secure-storage = { path = "../../secure/storage", version = "0.1.0" }
glob = "0.3.0"
sm = "0.9.0"
diem-config = { path = "../../config"}
ajson = "0.2.3"
hex = "0.4"
machine-ip = "0.2.1"
url = { version = "^2.1", features = ["serde"]}
diem-genesis-tool = { path = "../../config/management/genesis", version = "0.1.0" }
diem-wallet = { path = "../../testsuite/cli/diem-wallet", version = "0.1.0" }
diemdb = { path = "../../storage/diemdb", version = "0.1.0" }
diem-temppath = { path = "../../common/temppath", version = "0.1.0" }
ol-keys = { path = "../../ol/keys/", version = "0.1.0" }
abscissa_tokio = "0.5"
regex = "1"
ol-types = { path = "../../ol/types"}
storage-interface = { path = "../../storage/storage-interface", version = "0.1.0" }
fs_extra = "1"
port_scanner = "0.1.5"
backup-cli = { path = "../../storage/backup/backup-cli", version = "0.1.0" }
move-core-types = { path = "../../language/move-core/types" }
walkdir = "2.3"
rand = "0.8"
bcs = "0.1.2"
move-vm-types = { path = "../../language/move-vm/types" } # 0L todo: which move-vm/ path?
move-binary-format = { path = "../../language/move-binary-format" }
dialoguer = "0.8.0"
diem-crypto = { path = "../../crypto/crypto" }


# Parity with Storage create
[dependencies.rocksdb]
version = "0.15.0"
default-features = false
features = ["lz4"]

[dependencies.abscissa_core]
version = "0.5.2"
# optional: use `gimli` to capture backtraces
# see https://github.com/rust-lang/backtrace-rs/issues/189
# features = ["gimli-backtrace"]

[dev-dependencies]
abscissa_core = { version = "0.5.2", features = ["testing"] }
once_cell = "1.2"