[package]
name = "diem-transaction-replay"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Replay transactions stored on chain"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
structopt = "0.3.21"
hex = "0.4.3"
diem-workspace-hack = { path = "../../crates/diem-workspace-hack" }
diem-types = { path = "../../types" }
diem-state-view = { path = "../../storage/state-view" }
diem-validator-interface = { path = "../diem-validator-interface" }
diemdb = { path = "../../storage/diemdb" }
diem-vm = { path = "../diem-vm" }
move-binary-format = { git = "https://github.com/OLSF/move-0L", rev = "3a174c09c397ee78df1ef7bd2f4ea4205711f69b"}
move-cli = { git = "https://github.com/OLSF/move-0L", rev = "3a174c09c397ee78df1ef7bd2f4ea4205711f69b" }
move-vm-types = { git = "https://github.com/OLSF/move-0L", rev = "3a174c09c397ee78df1ef7bd2f4ea4205711f69b" }
move-core-types = { git = "https://github.com/OLSF/move-0L", rev = "3a174c09c397ee78df1ef7bd2f4ea4205711f69b" }
move-vm-runtime = { git = "https://github.com/OLSF/move-0L", rev = "3a174c09c397ee78df1ef7bd2f4ea4205711f69b" }
move-vm-test-utils = { git = "https://github.com/OLSF/move-0L", rev = "3a174c09c397ee78df1ef7bd2f4ea4205711f69b" }
diem-resource-viewer = { path = "../diem-resource-viewer" }
diem-framework = { path = "../../diem-move/diem-framework" }
move-compiler = { git = "https://github.com/OLSF/move-0L", rev = "3a174c09c397ee78df1ef7bd2f4ea4205711f69b" }
bcs = "0.1.2"
difference = "2.0.0"

[dev-dependencies]
vm-genesis = { path = "../vm-genesis" }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }
