[package]
name = "shuffle-custom-move-code"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
diem-framework = { path = "../../diem-move/diem-framework" }
diem-workspace-hack = { version = "0.1", path = "../../crates/diem-workspace-hack" }
diem-vm = { path = "../../diem-move/diem-vm" }
move-stdlib = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
move-unit-test = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
