owners = [
  "4C613C2F4B1E67CA8D98A542EE3F59F5",
  "88E74DFED34420F2AD8032148280A84B",
  "E660402D586AD220ED9BEFF47D662D54",
  "9E6BB3A75E9618FBA057E86E69338C94",
  "3DC18D1CF61FAAC6AC70E3A63F062E4B"
  ]
operators = [
  "4C613C2F4B1E67CA8D98A542EE3F59F5-oper",
  "88E74DFED34420F2AD8032148280A84B-oper",
  "E660402D586AD220ED9BEFF47D662D54-oper",
  "9E6BB3A75E9618FBA057E86E69338C94-oper",
  "3DC18D1CF61FAAC6AC70E3A63F062E4B-oper"
  ]
libra_root = "root"
treasury_compliance = "root"