version: "3.8"
services:
  debug:
    image: "${OL_IMAGE}"
    container_name: 0l-debug
    restart: "no"
    network_mode: "host"
    pid: "host"
    volumes:
      - node_data:/root/.0L
    entrypoint: [ "bash" ]
    ports:
      - 16179:6179
      - 16180:6180
      - 18080:8080
      - 13030:3030
    ulimits:
      nproc: 100000
      nofile: 100000

  fullnode:
    image: "${OL_IMAGE}"
    container_name: 0l-fullnode
    restart: "always"
    network_mode: "host"
    pid: "host"
    volumes:
      - node_data:/root/.0L
    entrypoint: ""
    command:
      [
        "diem-node",
        "--config",
        "/root/.0L/fullnode.node.yaml"
      ]
    ports:
      - 6179:6179
      - 6180:6180
      - 8080:8080
    ulimits:
      nproc: 100000
      nofile: 100000

  validator:
    image: "${OL_IMAGE}"
    container_name: 0l-validator
    restart: "always"
    network_mode: "host"
    pid: "host"
    volumes:
      - node_data:/root/.0L
    entrypoint: ""
    command:
      [
        "diem-node",
        "--config",
        "/root/.0L/validator.node.yaml"
      ]
    ports:
      - 6179:6179
      - 6180:6180
      - 8080:8080
    ulimits:
      nproc: 100000
      nofile: 100000

  tower:
    image: "${OL_IMAGE}"
    container_name: 0l-tower
    restart: "always"
    network_mode: "host"
    pid: "host"
    volumes:
      - node_data:/root/.0L
    # Todo (nourspace): find a way to toggle these modes using flags or env vars
    # mode 1: initial start uses upstream as fullnode/validator are not yet synced
    entrypoint: [ "tower", "--use-upstream-url", "--verbose", "start" ]
    # mode 2: fullnode/validator are synced
    #entrypoint: [ "tower", "--verbose", "start" ]
    # mode 3: run as operator while in validator mode
    #entrypoint: [ "tower", "--is-operator", "--verbose", "start" ]
    ulimits:
      nproc: 100000
      nofile: 100000
    environment:
      NODE_ENV: "prod"
      TEST: "y"
      MNEM: "${OL_MNEM}"

  monitor:
    image: "${OL_IMAGE}"
    container_name: 0l-monitor
    restart: "always"
    network_mode: "host"
    pid: "host" # required to detect processes?
    volumes:
      - node_data:/root/.0L
    entrypoint: [ "ol", "serve" ]
    ports:
      - 3030:3030
    ulimits:
      nproc: 100000
      nofile: 100000

volumes:
  node_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${OL_DATA_DIR}"
