[package]
name = "diem-framework-releases"
version = "0.1.0"
edition = "2018"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem Framework Releases"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false


[dependencies]
move-bytecode-verifier = { git = "https://github.com/OLSF/move-0L", rev = "087148a083076ddbb8b55ed0db343d235ab27cce" }
move-command-line-common = { git = "https://github.com/OLSF/move-0L", rev = "087148a083076ddbb8b55ed0db343d235ab27cce" }
diem-crypto = { path = "../../../../crates/diem-crypto" }
diem-types = { path = "../../../../types" }
diem-workspace-hack = { path = "../../../../crates/diem-workspace-hack" }
move-binary-format = { git = "https://github.com/OLSF/move-0L", rev = "087148a083076ddbb8b55ed0db343d235ab27cce" }
framework-releases = { path = "../../releases" }

anyhow = "1.0.52"
include_dir = "0.6.0"
bcs = "0.1.2"
once_cell = "1.7.2"

[dev-dependencies]
move-bytecode-verifier = { git = "https://github.com/OLSF/move-0L", rev = "087148a083076ddbb8b55ed0db343d235ab27cce" }
