[alias]
x = "run --package x --bin x --"
xcheck = "run --package x --bin x -- check"
xclippy = "run --package x --bin x -- clippy"
xfmt = "run --package x --bin x -- fmt"
xfix = "run --package x --bin x -- fix"
xtest = "run --package x --bin x -- test"
xlint = "run --package x --bin x -- lint"
xbuild = "run --package x --bin x -- build"
nextest = "run --package x --bin x -- nextest"

# //////// 0L ////////
[target.'cfg(target_os = "linux")']
# Dramatically increases the link performance for the eventbus
rustflags = ["-C", "link-arg=-fuse-ld=lld"] # sudo apt -y install lld
[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld"] # brew install michaeleisel/zld/zld