[package]
name = "backup-cli"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.org>"]
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.33"
async-trait = "0.1.41"
byteorder = "1.3.4"
bytes = "0.5.6"
dirs = "3.0.1"
futures = "0.3.6"
hex = "0.4.2"
itertools = "0.9.0"
once_cell = "1.4.1"
rand = "0.7.3"
regex = "1.3.9"
reqwest = { version = "0.10.8", features = ["stream"], default-features = false }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.58"
structopt = "0.3.18"
toml = "0.5.6"
tokio = { version = "0.2.22", features = ["full"] }
tokio-util = { version = "0.3.1", features = ["compat"] }

executor = { path = "../../../execution/executor", version = "0.1.0" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers", version = "0.1.0", optional = true }
executor-types = { path = "../../../execution/executor-types", version = "0.1.0" }
diem-jellyfish-merkle = { path = "../../jellyfish-merkle", version = "0.1.0" }
lcs = { path = "../../../common/lcs", package = "diem-canonical-serialization", version = "0.1.0" }
diem-crypto = { path = "../../../crypto/crypto", version = "0.1.0" }
diem-infallible = { path = "../../../common/infallible", version = "0.1.0" }
diem-logger = { path = "../../../common/logger", version = "0.1.0" }
diem-secure-push-metrics = { path = "../../../secure/push-metrics", version = "0.1.0" }
diem-types = { path = "../../../types", version = "0.1.0" }
diem-vm = { path = "../../../language/diem-vm", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
diemdb = { path = "../../diemdb", version = "0.1.0" }
storage-interface = { path = "../../storage-interface", version = "0.1.0" }

[dev-dependencies]
proptest = "0.10.1"

backup-service = { path = "../backup-service", version = "0.1.0" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers", version = "0.1.0" }
diemdb = { path = "../../diemdb", version = "0.1.0", features = ["fuzzing"] }
diem-config = { path = "../../../config", version = "0.1.0" }
diem-proptest-helpers = { path = "../../../common/proptest-helpers" }
diem-temppath = { path = "../../../common/temppath", version = "0.1.0" }
storage-interface = { path = "../../storage-interface", version = "0.1.0" }

[features]
fuzzing = ["diemdb/fuzzing"]
