[package]
name = "diem-writeset-generator"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Generating writesets used for incident management"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
structopt = "0.3.21"
tempfile = "3.2.0"
handlebars = "3.5.3"
hex = "0.4.3"
serde = { version = "1.0.124", default-features = false }
serde_json = "1.0.64"
once_cell = "1.7.2"

move-bytecode-verifier = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
diem-workspace-hack = { path = "../../crates/diem-workspace-hack" }
diem-crypto-derive = { path = "../../crates/diem-crypto-derive" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-types = { path = "../../types" }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }
diem-framework = { path = "../../diem-move/diem-framework" }
move-compiler = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
bcs = "0.1.2"
diem-state-view = { path = "../../storage/state-view" }
diem-validator-interface = { path = "../diem-validator-interface" }
diem-transaction-replay = { path = "../transaction-replay" }
diemdb = { path = "../../storage/diemdb" }
diem-vm = { path = "../diem-vm" }
move-binary-format = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37"}
move-vm-types = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
move-core-types = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
move-vm-runtime = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
move-vm-test-utils = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
read-write-set = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
#//////// 0L ///////
# cli = { path = "../../../testsuite/cli" }
diem-transaction-builder = { path = "../../sdk/transaction-builder" }
ol-types = { path = "../../ol/types" }
diem-resource-viewer = { path = "../diem-resource-viewer" }
move-resource-viewer = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }