[package]
name = "diem-writeset-generator"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Generating writesets used for incident management"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
structopt = "0.3.21"
tempfile = "3.2.0"
handlebars = "3.5.3"
hex = "0.4.3"
serde = { version = "1.0.124", default-features = false }
serde_json = "1.0.64"
once_cell = "1.7.2"

move-bytecode-verifier = { git = "https://github.com/OLSF/move-0L", rev = "9fa5ae30621027777c3a5776871b5760d95c9fdc" }
diem-workspace-hack = { path = "../../crates/diem-workspace-hack" }
diem-crypto-derive = { path = "../../crates/diem-crypto-derive" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-types = { path = "../../types" }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }
diem-framework = { path = "../../diem-move/diem-framework" }
move-compiler = { git = "https://github.com/OLSF/move-0L", rev = "9fa5ae30621027777c3a5776871b5760d95c9fdc" }
bcs = "0.1.2"
diem-state-view = { path = "../../storage/state-view" }
diem-validator-interface = { path = "../diem-validator-interface" }
diem-transaction-replay = { path = "../transaction-replay" }
diemdb = { path = "../../storage/diemdb" }
diem-vm = { path = "../diem-vm" }
move-binary-format = { git = "https://github.com/OLSF/move-0L", rev = "9fa5ae30621027777c3a5776871b5760d95c9fdc"}
move-vm-types = { git = "https://github.com/OLSF/move-0L", rev = "9fa5ae30621027777c3a5776871b5760d95c9fdc" }
move-core-types = { git = "https://github.com/OLSF/move-0L", rev = "9fa5ae30621027777c3a5776871b5760d95c9fdc" }
move-vm-runtime = { git = "https://github.com/OLSF/move-0L", rev = "9fa5ae30621027777c3a5776871b5760d95c9fdc" }
move-vm-test-utils = { git = "https://github.com/OLSF/move-0L", rev = "9fa5ae30621027777c3a5776871b5760d95c9fdc" }
read-write-set = { git = "https://github.com/OLSF/move-0L", rev = "9fa5ae30621027777c3a5776871b5760d95c9fdc" }
