[package]
name = "diem-vm"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem VM runtime"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
fail = "0.4.0"
once_cell = "1.7.2"
rayon = "1.5.0"
mirai-annotations = "1.10.1"
tracing = "0.1.16"

bcs = "0.1.2"
diem-crypto = { path = "../../crates/diem-crypto" }
diem-logger = { path = "../../crates/diem-logger" }
diem-metrics = { path = "../../crates/diem-metrics" }
diem-state-view = { path = "../../storage/state-view" }
diem-types = { path = "../../types" }
diem-workspace-hack = { path = "../../crates/diem-workspace-hack" }
move-core-types = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
move-vm-runtime = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
move-vm-types = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
move-binary-format = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
move-bytecode-utils = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
move-stdlib = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37" }
diem-framework = { path = "../../diem-move/diem-framework" }
serde_json = "1.0.64"
serde = { version = "1.0.124", default-features = false }
read-write-set-dynamic = { git = "https://github.com/OLSF/move-0L", rev = "f16172cfe44af336bc20187e85811e4bd9815e37"}

mvhashmap = { path = "../mvhashmap" }
diem-parallel-executor = {path = "../parallel-executor" }

#/////// 0L /////////
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }

[dev-dependencies]
proptest = "1.0.0"

diem-types = { path = "../../types", features = ["fuzzing"] }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }

[features]
default = []
mirai-contracts = []
fuzzing = ["move-binary-format/fuzzing","move-vm-types/fuzzing"]
failpoints = ["fail/failpoints", "move-vm-runtime/failpoints"]
