[package]
name = "ol-keys"
authors = []
version = "0.1.0"
edition = "2018"

[dependencies]
rpassword = "5.0"
diem-wallet = { path = "../../testsuite/cli/diem-wallet", version = "0.1.0" }
diem-types = { path = "../../types/", version = "0.0.1" }