[package]
name = "vm-genesis"
version = "0.1.0"
edition = "2018"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem vm genesis"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.52"
once_cell = "1.7.2"
rand = "0.8.3"

move-bytecode-verifier = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
bcs = "0.1.2"
diem-config = { path = "../../config" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-state-view = { path = "../../storage/state-view" }
diem-types = { path = "../../types" }
# diem-workspace-hack = 
move-bytecode-utils = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
move-core-types = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
move-vm-runtime = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra"}
move-vm-types = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
diem-framework = { path = "../../diem-move/diem-framework" }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }
diem-transaction-builder = { path = "../../sdk/transaction-builder"}
move-binary-format = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
diem-vm = { path = "../diem-vm" }
read-write-set = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
# //////// 0L ////////
diem-global-constants = { path = "../../config/global-constants" }
hex = "0.4"
serde = { version = "1.0.116", features = ["rc"], default-features = false }
ol-types = {path = "../../ol/types"}

diem-logger = { path = "../../crates/diem-logger" }
indicatif = "0.17.3"


[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
diem-proptest-helpers = { path = "../../crates/diem-proptest-helpers" }

[features]
default = []
fuzzing = ["diem-types/fuzzing", "move-vm-types/fuzzing"]
