[package]
name = "diem-writeset-generator"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
description = "Generating writesets used for incident management"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.32"
structopt = "0.3.18"
tempfile = "3.1.0"
handlebars = "3.5.0"
serde = { version = "1.0.116", default-features = false }
serde_json = "1.0.58"

diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
diem-types = { path = "../../../types", version = "0.1.0" }
stdlib = { path = "../../stdlib", version = "0.1.0" }
move-lang = { path = "../../move-lang", version = "0.0.1" }
lcs = { path = "../../../common/lcs", version = "0.1.0", package = "diem-canonical-serialization" }
