[package]
name = "move-vm-natives"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move VM native functions"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.7.2"
mirai-annotations = "1.10.1"
sha2 = "0.9.3"
smallvec = "1.6.1"

diem-crypto = { path = "../../../crypto/crypto" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
move-core-types = { path = "../../move-core/types" }
move-vm-types = { path = "../types" }
move-binary-format = { path = "../../move-binary-format" }
diem-metrics = { path = "../../../common/metrics" }

######### 0L ########
diem-global-constants = { path = "../../../config/global-constants"}
hex = "0.4.2"
diem-types = { path = "../../../types"}
vdf = { path="../../../ol/verifiable_delay/vdf"}
rust_decimal= { version = "1.14.2", default-features = true, features = ["maths"] }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
ethers = {version = "0.1.3"}


[features]
default = []
debug_module = []
