[package]
name = "diem-log-derive"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.org>"]
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[lib]
proc-macro = true

[dependencies]
diem-workspace-hack = { path = "../../workspace-hack", version = "0.1.0" }
syn = { version = "1.0.42", features = ["extra-traits"] }
quote = "1.0.7"
proc-macro2 = "1.0.24"
