[package]
name = "compiler"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
description = "Libra compiler"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.33"
bytecode-verifier = { path = "../bytecode-verifier", version = "0.1.0" }
ir-to-bytecode = { path = "ir-to-bytecode", version = "0.1.0" }
bytecode-source-map = { path = "bytecode-source-map", version = "0.1.0" }
compiled-stdlib = { path = "../stdlib/compiled",  version = "0.1.0" }
diem-types = { path = "../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }
move-ir-types = { path = "../move-ir/types", version = "0.1.0" }
vm = { path = "../vm", version = "0.1.0" }
lcs = { path = "../../common/lcs", version = "0.1.0", package = "diem-canonical-serialization" }
structopt = "0.3.18"
serde_json = "1.0.58"

[features]
default = []
fuzzing = ["diem-types/fuzzing"]
