[package]
name = "diem-e2e-tests-replay"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "A tool that reconstructs and replays test cases from the trace dump of E2E tests"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.52"
bcs = "0.1.2"
structopt = "0.3.21"
walkdir = "2.3.1"

diem-workspace-hack = { path = "../../crates/diem-workspace-hack" }
move-stackless-bytecode-interpreter = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
diem-types = { path = "../../types", features = ["fuzzing"] }
diem-framework = { path = "../../diem-move/diem-framework" }
diem-vm = { path = "../../diem-move/diem-vm" }
language-e2e-tests = { path = "../e2e-tests" }
move-binary-format = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
move-core-types = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
move-model = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
move-vm-runtime = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
move-vm-types = { git = "https://github.com/OLSF/move-0L", rev = "86a9cfd1f0ace08c8c4220f7927e112c1f990945" }
