[package]
name = "diem-transactional-test-harness"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Transactional testing framework for Move"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.6.1"
once_cell = "1.7.2"
anyhow = "1.0.52"
structopt = "0.3.21"
bcs = "0.1.2"
hex = "0.4.3"
rand = "0.8.3" #/////// 0L /////////

# Move dependencies
move-transactional-test-runner = { git = "https://github.com/OLSF/move-0L", rev = "3a174c09c397ee78df1ef7bd2f4ea4205711f69b" }
move-compiler = { git = "https://github.com/OLSF/move-0L", rev = "3a174c09c397ee78df1ef7bd2f4ea4205711f69b" }
move-binary-format = { git = "https://github.com/OLSF/move-0L", rev = "3a174c09c397ee78df1ef7bd2f4ea4205711f69b" }
move-core-types = { git = "https://github.com/OLSF/move-0L", rev = "3a174c09c397ee78df1ef7bd2f4ea4205711f69b" }
move-command-line-common = { git = "https://github.com/OLSF/move-0L", rev = "3a174c09c397ee78df1ef7bd2f4ea4205711f69b" }

# Diem-Move dependencies
language-e2e-tests = { path = "../e2e-tests" }
diem-vm =  { path = "../diem-vm" }
vm-genesis= { path = "../vm-genesis" }
diem-framework = { path = "../diem-framework" }
diem-keygen = { path = "../diem-keygen" }

# Other Diem dependencies
diem-types = { path = "../../types", features = ["fuzzing"] }
diem-transaction-builder = { path = "../../sdk/transaction-builder" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-state-view = { path = "../../storage/state-view" }
diem-workspace-hack = { version = "0.1", path = "../../crates/diem-workspace-hack" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[test]]
name = "tests"
harness = false
