[package]
name = "diem-genesis-tool"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.org>"]
description = "A tool to manage genesis"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.33"
rand = "0.7.3"
serde = { version = "1.0.116", features = ["rc"], default-features = false }
structopt = "0.3.18"
thiserror = "1.0.21"
toml = { version = "0.5.6", default-features = false }

consensus-types = { path = "../../../consensus/consensus-types", version = "0.1.0" }
executor = { path = "../../../execution/executor", version = "0.1.0" }
generate-key = { path = "../../../config/generate-key", version = "0.1.0" }
lcs = { path = "../../../common/lcs", version = "0.1.0", package = "diem-canonical-serialization" }
diem-config = { path = "../..", version = "0.1.0"}
diem-crypto = { path = "../../../crypto/crypto", version = "0.1.0" }
diem-global-constants = { path = "../../../config/global-constants", version = "0.1.0" }
diem-management = { path = "..", version = "0.1.0" }
diem-network-address = { path = "../../../network/network-address", version = "0.1.0" }
diem-network-address-encryption = {path = "../network-address-encryption", version = "0.1.0"}
diem-secure-json-rpc = { path = "../../../secure/json-rpc", version = "0.1.0" }
diem-secure-storage = { path = "../../../secure/storage", version = "0.1.0" }
diem-secure-time = { path = "../../../secure/time", version = "0.1.0" }
diem-types = { path = "../../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
diem-temppath = { path = "../../../common/temppath", version = "0.1.0" }
diem-vm = { path = "../../../language/diem-vm", version = "0.1.0" }
diemdb = { path = "../../../storage/diemdb", version = "0.1.0" }
storage-interface = { path = "../../../storage/storage-interface", version = "0.1.0" }
transaction-builder = { path = "../../../language/transaction-builder", version = "0.1.0" }
vm-genesis = { path = "../../../language/tools/vm-genesis", version = "0.1.0" }

######## 0L
rustyline = "6.2.0"
diem-wallet = { path = "../../../testsuite/cli/diem-wallet", version = "0.1.0"}
# miner = { path = "../../../miner", version = "0.1.0" }
hex = "0.4.2"
dirs = "2.0.2"
serde_json = "1"


[dev-dependencies]
diem-config = { path = "../..", version = "0.1.0", features = ["fuzzing"]}

[features]
testing = []
fuzzing = ["diem-config/fuzzing"]
