name: Integration

on:
  push:
    branches: [ main, ci, v5 ]
  pull_request:
    branches: [ main, 'release**', v5]
    
jobs:
  integration:
    name: Integration
    runs-on: self-hosted
    timeout-minutes: 90
    env:
      NODE_ENV: test
      TEST: y
    steps:
      - uses: actions/checkout@v3
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.52.1
            override: true
            components: rustfmt, clippy
      - name: Install deps
        run: sudo apt-get install -y lld
      - name: Check branch
        run: echo "${{ steps.branch-name.outputs.current_branch }}"
      - name: Build sdlib
        run: cargo r -p diem-framework --release
        
      - name: MINING
        run: RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-mining.mk test

      # - name: MINING ACROSS EPOCHS
      #   run: RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-mining-epochs.mk test

      - name: ONBOARD
        run: RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-onboard.mk test
      - name: File permissions
        run: sudo chmod -R 777 language/*

      - name: UPGRADE
        run: BRANCH_NAME=${{ steps.branch-name.outputs.current_branch }} RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-upgrade.mk test

      - name: AUTOPAY percent-change
        run: RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-autopay.mk test-percent-bal
      - name: AUTOPAY fixed-once
        run: RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-autopay.mk test-fixed-once
      - name: AUTOPAY all
        run: RUSTC_WRAPPER=sccache SOURCE_PATH=./ make -f ol/integration-tests/test-autopay.mk test
