name: Publish

on:
  push:
#    tags:
#      - '*'
     branch:
       - cargo-deb

env:
  CARGO_TERM_COLOR: always
  NODE_ENV: prod

jobs:
  publish:
    name: Publish for Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - run: sudo apt install -y cmake clang llvm libgmp-dev pkg-config libssl-dev
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-deb
      # - run: cargo build --exclude libra-fuzzer --exclude cluster-test --exclude libra-fuzz --workspace --release
      # - run: cd miner & cargo build --release
      - run: cargo deb -p miner --deb-version ${{ github.ref }} -- -p miner --release
      - uses: actions/upload-artifact@v2
        with:
          name: miner
          path: ./target/debian/*
#      - name: Upload binaries to release
#        uses: svenstaro/upload-release-action@v1-release
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: target/release/${{ matrix.artifact_name }}
#          asset_name: ${{ matrix.asset_name }}
#          tag: ${{ github.ref }}
