name: Publish

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always
  NODE_ENV: prod

jobs:
  release:
    name: Release for OLSF
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: rustfmt
      - name: Build
        run:  make bins
      - name: Upload binaries to github.com/release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/!(*.*)
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
