[package]
name = "genesis-viewer"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
description = "Libra genesis viewer"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
lcs = { path = "../../../common/lcs", version = "0.1.0", package = "diem-canonical-serialization" }
diem-types = { path = "../../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
vm = { path = "../../vm", version = "0.1.0" }
resource-viewer = { path = "../resource-viewer", version = "0.1.0"}
vm-genesis = { path = "../vm-genesis", version = "0.1.0" }
compiled-stdlib = { path = "../../stdlib/compiled",  version = "0.1.0" }

structopt = "0.3.18"
